### ISSUE TITLE
Various bugs running the scripts [briatte/parlement]

### ISSUE THREAD

**Issue by Free16t** [briatte/parlviz#1]
Hi, 

I was trying to use it yet, I'm facing various bug with yours scripts. 
Here is the output of R, did you ever see any of those errors? 

```
> Parsing 1690 MPs
> Error in UseMethod("xmlNamespaceDefinitions") : 
  no applicable method for "xmlNamespaceDefinitions" applied to an object of class "NULL"
> source("dossiers-an.r")
Error in 1 + str_count(doc$au, ";") : 
  non-numeric argument to binary operator
> source("build-an.r")
Error in zip("net_fr_an.zip", dir(pattern = "^net_fr_an\\d{1,2}\\.gexf$")) : 
  'files' must a character vector specifying one or more filepaths
> source("comm-an.r")
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file 'data/net_fr_an.rda', probable reason 'No such file or directory'
> 
> source("sponsors-se.r")
Parsing 1250 anciens-senateurs 
Error in download.file(link, file, mode = "wb", quiet = TRUE) : 
  cannot open destfile 'raw_se/senateur/abadie_francois83008p.html', reason 'No such file or directory'
Error in if (!file.info(file)$size) { : 
  missing value where TRUE/FALSE needed
> source("dossiers-se.r")
Error in `[.data.frame`(sp, , c("autcod", "autfct", "name", "party", "url")) : 
  undefined columns selected
> source("build-se.r")
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'data/sponsors-se.csv': No such file or directory
> source("comm-se.r")
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file 'data/net_fr_se.rda', probable reason 'No such file or directory'
> 
> have a nice day
> q()
> 
have a nice day
```

Sincerely

**Comment by briatte** [comment]
Hi,

I assume that you are referring to the scripts at [briatte/parlement](https://github.com/briatte/parlement) rather than to the `parlviz` repository.

It's hard to tell from your output what exactly the issue(s) is (are), as it does not contain the faulty line numbers. Please open one or more issues at [briatte/parlement](https://github.com/briatte/parlement) with that information.

A few pointers from what I can read in your console output:

```
Error in UseMethod("xmlNamespaceDefinitions") : 
  no applicable method for "xmlNamespaceDefinitions" applied to an object of class "NULL"
```

This could be that you failed downloading a file, and tried to parse a zero-size file instead of the actual web page. Remove any null-sized file from your raw data folder(s).

```
Error in zip("net_fr_an.zip", dir(pattern = "^net_fr_an\\d{1,2}\\.gexf$")) : 
  'files' must a character vector specifying one or more filepaths
```

That error is probably due to the fact that you failed to generate any GEXF file in the first place (although I cannot guess that from the output).

```
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
```

This could be anything from a network error to a null-sized file issue like the one I suggest above.

```
Error in download.file(link, file, mode = "wb", quiet = TRUE) : 
  cannot open destfile 'raw_se/senateur/abadie_francois83008p.html', reason 'No such file or directory'
```

Have you created the `raw_se` folder? It should have been created by the `make.r` script, which should be your starting point.

```
Error in if (!file.info(file)$size) { : 
  missing value where TRUE/FALSE needed
```

This makes sense given the error just before it.

```
Error in `[.data.frame`(sp, , c("autcod", "autfct", "name", "party", "url")) : 
  undefined columns selected
```

Looks like the script did not find the right columns in the SQL database. Have you set up PostgreSQL properly by importing the Ameli DB from data.senat.fr? (See the [README](https://github.com/briatte/parlement/blob/master/README.md) file for quick instructions.)

```
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'data/sponsors-se.csv': No such file or directory
```

This makes sense given all previous errors.

---

Your errors seem to suggest that you are having a hard time downloading the data, rather than parsing it. Some other errors further suggest that you are lacking the correct folder structure to download the data. At that stage, I'd recommend going through the [README](https://github.com/briatte/parlement/blob/master/README.md) file again, running `make.r` again in RStudio or any interface that will stop on the first error, and report that error in the issues of [briatte/parlement](https://github.com/briatte/parlement).

Since the entire download routine that you are trying to replicate is rather long, I can send you the data directly if you send me an email to request it, but I cannot help much with setting up SQL on your machine, which you will almost certainly need to do at some point if you want to build the network objects for the French Senate.
